#!/bin/sh
set -e

# JWT keypair (lexik/jwt-authentication-bundle): config/jwt/*.pem is
# gitignored (private keys must never be committed), and unlike a
# Codespace - where this was generated by hand once as part of the
# manual bootstrap checklist (README "Points d'attention" #11) - a
# Render Docker deploy has no separate "build command" step to run it
# in. The container just booted straight into apache2-foreground with
# no keypair, which stayed invisible: /api/health and every read
# endpoint (funding, sources...) work fine with no keys at all, only
# /api/auth/login (the only place a JWT actually gets signed) 500s.
#
# Generated on every container start rather than baked into the image:
# idempotent (skipped once the files already exist - e.g. a mounted
# persistent disk across restarts of the same instance), and avoids
# committing a keypair - even a throwaway one - into a Docker image
# that could be pulled/inspected by anyone with registry access.
if [ ! -f config/jwt/private.pem ] || [ ! -f config/jwt/public.pem ]; then
  mkdir -p config/jwt
  php bin/console lexik:jwt:generate-keypair --no-interaction
  chown -R www-data:www-data config/jwt
fi

exec "$@"
