<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260829105710 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'B1.4: create the emission table (CO2 emissions by country/year, SCD2 historization)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE emission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, value_mt NUMERIC(10, 3) NOT NULL, collection_date DATE NOT NULL, validation_status VARCHAR(20) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_current BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, country_id INT NOT NULL, source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F0225CF4953C1C61 ON emission (source_id)');
        $this->addSql('CREATE INDEX idx_emission_country ON emission (country_id)');
        $this->addSql('CREATE INDEX idx_emission_year ON emission (year)');
        $this->addSql('CREATE INDEX idx_emission_collection_date ON emission (collection_date)');
        // Partial index (WHERE is_current = true) - same mechanism as funding's, see the
        // comment above #[ORM\UniqueConstraint] on Emission.php.
        $this->addSql('CREATE UNIQUE INDEX uniq_emission_dedup_key_current ON emission (source_id, country_id, year) WHERE is_current = true');
        $this->addSql('ALTER TABLE emission ADD CONSTRAINT FK_F0225CF4F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE emission ADD CONSTRAINT FK_F0225CF4953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE');
        // The auto-generated diff also proposed dropping/recreating funding's own partial
        // unique index - the known Doctrine/DBAL false positive documented on Funding.php
        // (the Postgres schema comparator can't read back a partial index's WHERE clause, so
        // it always sees it as "different" even when it's already correct). That no-op
        // drop/recreate was removed from this migration - see README point 3 and the
        // Funding.php UniqueConstraint comment.
    }

    public function down(Schema $schema): void
    {
        // The auto-generated diff also proposed recreating the TimescaleDB internal catalog
        // schemas (timescaledb_information, _timescaledb_internal, etc.) - a known leak into
        // doctrine:migrations:diff output despite the schema_filter in doctrine.yaml (README
        // point 3). Removed manually; those schemas are TimescaleDB's own and must never be
        // touched by an application migration.
        $this->addSql('ALTER TABLE emission DROP CONSTRAINT FK_F0225CF4F92F3E70');
        $this->addSql('ALTER TABLE emission DROP CONSTRAINT FK_F0225CF4953C1C61');
        $this->addSql('DROP TABLE emission');
    }
}
