<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260829232613 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'B1.5: create the processed_document table (PDF-extraction hash cache)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE processed_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, hash VARCHAR(64) NOT NULL, source_name VARCHAR(255) NOT NULL, source_url VARCHAR(500) NOT NULL, minio_path VARCHAR(500) NOT NULL, rows_extracted INT NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_processed_document_hash ON processed_document (hash)');
        // The auto-generated diff also proposed dropping/recreating the funding and emission
        // tables' own partial unique indexes - the known Doctrine/DBAL false positive documented
        // on Funding.php (the Postgres schema comparator can't read back a partial index's WHERE
        // clause). No-op, removed - see README point 3.
    }

    public function down(Schema $schema): void
    {
        // The auto-generated diff also proposed recreating the TimescaleDB internal catalog
        // schemas - a known leak into doctrine:migrations:diff output despite the schema_filter
        // in doctrine.yaml (README point 3). Removed manually.
        $this->addSql('DROP TABLE processed_document');
    }
}
