<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260831182209 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create funding_project_contribution (fixes the real Funding double-counting bug)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE funding_project_contribution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, project_id VARCHAR(255) NOT NULL, year INT NOT NULL, funding_type VARCHAR(20) NOT NULL, amount NUMERIC(15, 2) NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_id INT NOT NULL, country_id INT NOT NULL, sector_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A9844C6953C1C61 ON funding_project_contribution (source_id)');
        $this->addSql('CREATE INDEX IDX_3A9844C6F92F3E70 ON funding_project_contribution (country_id)');
        $this->addSql('CREATE INDEX IDX_3A9844C6DE95C867 ON funding_project_contribution (sector_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_funding_project_contribution_key ON funding_project_contribution (source_id, project_id, country_id)');
        $this->addSql('ALTER TABLE funding_project_contribution ADD CONSTRAINT FK_3A9844C6953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE funding_project_contribution ADD CONSTRAINT FK_3A9844C6F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE funding_project_contribution ADD CONSTRAINT FK_3A9844C6DE95C867 FOREIGN KEY (sector_id) REFERENCES sector (id) NOT DEFERRABLE');
        // The auto-generated diff also proposed dropping/recreating funding's and
        // emission's own partial unique indexes - the known Doctrine/DBAL false
        // positive documented on Funding.php (the Postgres schema comparator can't
        // read back a partial index's WHERE clause). No-op, removed - see README
        // point 3. It also proposed `ALTER TABLE country ADD currency VARCHAR(3)` -
        // a real but unrelated pending change (Country.php already declares this
        // field) that belongs to whoever's task is adding it, not this one - left
        // out to keep this migration scoped to funding_project_contribution only.
    }

    public function down(Schema $schema): void
    {
        // The auto-generated diff also proposed recreating the TimescaleDB internal
        // catalog schemas - a known leak into doctrine:migrations:diff output
        // despite the schema_filter in doctrine.yaml (README point 3). Removed
        // manually.
        $this->addSql('ALTER TABLE funding_project_contribution DROP CONSTRAINT FK_3A9844C6953C1C61');
        $this->addSql('ALTER TABLE funding_project_contribution DROP CONSTRAINT FK_3A9844C6F92F3E70');
        $this->addSql('ALTER TABLE funding_project_contribution DROP CONSTRAINT FK_3A9844C6DE95C867');
        $this->addSql('DROP TABLE funding_project_contribution');
    }
}
