<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260824013715 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_key (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, key_hash VARCHAR(255) NOT NULL, status VARCHAR(20) DEFAULT \'active\' NOT NULL, quota INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C912ED9DA76ED395 ON api_key (user_id)');
        $this->addSql('CREATE TABLE funding (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, amount NUMERIC(15, 2) NOT NULL, original_amount NUMERIC(15, 2) DEFAULT NULL, original_currency VARCHAR(3) DEFAULT NULL, exchange_rate NUMERIC(12, 6) DEFAULT NULL, funding_type VARCHAR(20) NOT NULL, collection_date DATE NOT NULL, validation_status VARCHAR(20) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_current BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, country_id INT NOT NULL, sector_id INT NOT NULL, source_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D30DD1D6953C1C61 ON funding (source_id)');
        $this->addSql('CREATE INDEX idx_funding_country ON funding (country_id)');
        $this->addSql('CREATE INDEX idx_funding_sector ON funding (sector_id)');
        $this->addSql('CREATE INDEX idx_funding_year ON funding (year)');
        $this->addSql('CREATE INDEX idx_funding_collection_date ON funding (collection_date)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_type VARCHAR(20) NOT NULL, content TEXT NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE TABLE report (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, region VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, publication_date DATE DEFAULT NULL, status VARCHAR(20) DEFAULT \'draft\' NOT NULL, pdf_file VARCHAR(255) NOT NULL, download_count INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, country_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C42F7784F92F3E70 ON report (country_id)');
        $this->addSql('ALTER TABLE api_key ADD CONSTRAINT FK_C912ED9DA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE funding ADD CONSTRAINT FK_D30DD1D6F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE funding ADD CONSTRAINT FK_D30DD1D6DE95C867 FOREIGN KEY (sector_id) REFERENCES sector (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE funding ADD CONSTRAINT FK_D30DD1D6953C1C61 FOREIGN KEY (source_id) REFERENCES source (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // Note: doctrine:migrations:diff also listed CREATE SCHEMA statements
        // here for TimescaleDB's own internal schemas (see Version20260824005839
        // for the same issue and explanation). Removed manually so down() stays
        // symmetric with up() and safely re-runnable.
        $this->addSql('ALTER TABLE api_key DROP CONSTRAINT FK_C912ED9DA76ED395');
        $this->addSql('ALTER TABLE funding DROP CONSTRAINT FK_D30DD1D6F92F3E70');
        $this->addSql('ALTER TABLE funding DROP CONSTRAINT FK_D30DD1D6DE95C867');
        $this->addSql('ALTER TABLE funding DROP CONSTRAINT FK_D30DD1D6953C1C61');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE report DROP CONSTRAINT FK_C42F7784F92F3E70');
        $this->addSql('DROP TABLE api_key');
        $this->addSql('DROP TABLE funding');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE report');
    }
}
