<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260824005839 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE country (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, iso_code VARCHAR(3) NOT NULL, region VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5373C96662B6A45E ON country (iso_code)');
        $this->addSql('CREATE TABLE sector (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4BA3D9E85E237E06 ON sector (name)');
        $this->addSql('CREATE TABLE source (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(30) NOT NULL, reliability VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password_hash VARCHAR(255) NOT NULL, role VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1483A5E9E7927C74 ON users (email)');
    }

    public function down(Schema $schema): void
    {
        // Note: doctrine:migrations:diff also listed CREATE SCHEMA statements
        // here for TimescaleDB's own internal schemas (timescaledb_information,
        // timescaledb_experimental, _timescaledb_internal, _timescaledb_functions,
        // _timescaledb_config, _timescaledb_catalog, _timescaledb_cache). Those
        // schemas are owned by the extension and already exist outside of this
        // migration's control; removed manually so down() stays symmetric with
        // up() and safely re-runnable.
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE sector');
        $this->addSql('DROP TABLE source');
        $this->addSql('DROP TABLE users');
    }
}
